### ISSUE TITLE
Add more complex user input parsing

### ISSUE THREAD

**Issue by AaronLeoCooper** [AaronLeoCooper/tba-creator#18]
**Description**

The initial user input parser implementation means that phrases will be matched regardless of the order of words in the user's input: `open the door` works just as well as `door the open`. For greater control over this, additional options should be added globally & locally for response grammar arrays.

**Todo**

- [ ] Global option to toggle `strictGrammarOrder`
- [ ] Include existing global `caseSensitive` option in parsing (missed in initial release)
- [ ] Scene response options for:
  - [ ] `strictGrammarOrder`
  - [ ] `caseSensitive`
