### ISSUE TITLE
Add schema validator

### ISSUE THREAD

**Issue by AaronLeoCooper** [AaronLeoCooper/tba-creator#2]
**Description**

Given that the schema files are hand-written, it's important to have pre-runtime validation in place both as a command and as a step just before starting the main TBA.

**Todo**

- [x] Create a validator script to parse all schema files in a directory with descriptive errors
- [x] Create a command or flag to run validation once
- [x] Add validation step before normal TBA runtime
