### ISSUE TITLE
Add player state

### ISSUE THREAD

**Issue by AaronLeoCooper** [AaronLeoCooper/tba-creator#26]
**Description**

It's common for Text-Based Adventure games & Create-Your-Own-Adventure books to have a basic persistent player state, which can be used for things like player inventory or player stats. TBA Game should support a flexible state model that can be configured via schema config and interacted with by the player and in scenes.

Example state definition (not final, requires refinement)

```
[state.health]
  phrase = "misc.health"
  type = "number"
  initialValue = 100

  [[state.health.actions]]
    phrase = "actions.inspect"
    event = "print"

[state.inventory]
  phrase = "misc.inventory"
  type = "list"
  maximum = 10
  maximumMessage = "Your inventory is full, you'll have to drop something first!"

  [[state.inventory.actions]]
    phrase = "actions.inspect"
    event = "print"
    prefix = "You're currently holding "

  [[state.inventory.listActions]]
    phrase = "action.inspect"
    event = "print"

  [[state.inventory.listActions]]
    phrase = "action.drop"
    event = "remove"
    confirmMessage = "Are you sure you want to drop this? You'll loose it forever!"
    prefix = "You dropped your "
```

**Todo**

- [ ] Add new "state" schema definition, including:
  - [ ] User-defined state interactions by the player (e.g., inspecting or using state values like objects or player stats)
- [ ] Add state requirements/interactions in scene definitions:
  - [ ] Scene response requires X state to be Y value
  - [ ] Conditional scene description when state X is Y value
  - [ ] Scene response can update state values
