### ISSUE TITLE
Add support for text formatting

### ISSUE THREAD

**Issue by AaronLeoCooper** [AaronLeoCooper/tba-creator#30]
**Description**

Since most terminal environments support some rudimentary formatting like colours and text emphasis, it would be nice to support inline formatting in descriptions for scenes & responses.

**Todo**

- [ ] Define & implement syntax parsing to cover:
  - [ ] Colours
  - [ ] Bold & underline text
- [ ] Ensure any changes do not affect the output text when the environment doesn't support formatting
