### ISSUE TITLE
Main story entrypoint & game loop

### ISSUE THREAD

**Issue by AaronLeoCooper** [AaronLeoCooper/tba-creator#4]
**Description**

After all schema files are loaded and validated, the story should be loaded using the main program entrypoint. The game loop should be started, the first story scene description should be displayed and the program should then prompt for user input.

**Todo**

- [x] Entry point script for the story to begin
- [x] Display the first scene description
- [x] Display a user input prompt
