### ISSUE TITLE
Add advanced schema validation rules

### ISSUE THREAD

**Issue by AaronLeoCooper** [AaronLeoCooper/tba-creator#6]
**Description**

There should be more advanced validation logic in place to handle the below scenarios not caught by the basic validation rules.

**Todo**

- Main schema
  - [x] No `quitPhrases` or `unknownPhraseWarnings`
- Dictionary schema
  - [x] Phrases without a name
  - [x] Duplicate phrase type + name combinations
- Story schema
  - [x] Duplicate scene names
  - [x] Scenes that don't have any of these: `ending`, `responses`, `nextScene`
  - [x] Scene responses without `grammar`
  - [x] Scene responses without any of these: `nextScene`, `description`
  - [x] Scene response grammar entries that have invalid phrases
  - [x] Scene response `nextScene` references that point to invalid scene names

**Comment by AaronLeoCooper** [comment]
Resolved by #33
