### ISSUE TITLE
Input parsing & scene routing

### ISSUE THREAD

**Issue by AaronLeoCooper** [AaronLeoCooper/tba-creator#8]
**Description**

Once a scene has loaded and the program is ready to accept user input, the user's text needs to be parsed and matched against the scene's response grammar definitions.

**Todo**

- [x] Parse the user's input and attempt to match it to a scene response
- [x] Upon successfully matching a scene response, go to the response `nextScene`
- [x] Upon failing to match a scene response, randomly choose from and display one of the available global options for unknown phrase
