### ISSUE TITLE
Add special scene cases

### ISSUE THREAD

**Issue by AaronLeoCooper** [AaronLeoCooper/tba-creator#9]
**Description**

Handling is required for final scenes, scenes with a default `nextScene` option and pre/post scene display delays. Handling is also required for exiting the game when one of the global option exit phrases is typed.

**Todo**

- [x] Display the final scene based on `ending` and gracefully exit the program
- [x] Add scene delay handling based on global pre/post delay options
- [x] Add game exit/quit handling based on global exit phrase option
